#!/bin/bash
#chkconfig: 2345 10 90
. /etc/init.d/functions

prog=test
path=/usr/bin/

start(){
	cd $path
	python $prog start
	echo -n $"Starting $prog: "
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ]
        return $RETVAL
}
stop(){
	cd $path
	python $prog stop
	echo -n $"Shutting down $prog: "
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] 
        return $RETVAL
}
status(){
	cd $path
	python $prog status
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
status)
	status
	;;
*)
	echo $"Usage: $0 {start|stop|restart|status}"
esac
