#!/usr/bin/python

import xdaemon,time,sys

def test(a):
    while True:
        #with open('/root/aa.txt','a+') as f:
        #    f.write('%s' % a)
        #    f.close()
        print a
	time.sleep(5)

t=xdaemon.Daemon(target=test,args=('aa',))
if sys.argv[1] == 'start':
    t.start()
elif sys.argv[1] == 'stop':
    t.stop()
elif sys.argv[1] == 'restart':
    t.stop()
    t.start()
elif sys.argv[1] == 'status':
    t.status()
else:
    print "Usage: python %s [start|stop|restart|status]" % sys.argv[0]
